channels:
- conda-forge
dependencies:
- git
- pip
- python
- pyiron_gui >= 0.0.4
- iprpy-data
- gpaw
- nglview
- seaborn
- pyscal
- jupyterlab
- pyiron-data >=0.0.5
- sqsgenerator
- pymatgen
- hyperspy
# - lammps
# - sphinxdft >=2.7.0
# - sphinxdft-data
